def method_with_exception():
    raise Exception("test exception")


method_with_exception()
